language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
      - node_modules
before_script:
      - npm install -g mocha
after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"

