language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
      - node_modules
script: yarn run test:Mock --silent
before_script:
      - yarn global add mocha
after_script: "yarn run coverage"

